[workspace]
resolver = "2"
members = [
    "crates/vcad-wasm",
    "crates/server",
    "crates/shared",
    "crates/gui",
]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
